spring:
  application:
    name: BookConnect
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/book_connect
    username: replaceMeUsername
    password: replaceMePassword
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  default-consumes-media-type: application/json
  file:
    upload:
      photos-output-path: ./uploads

logging:
  level:
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: health

user:
  config:
    jwt-secret-key:
    allowed-origin:
